# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0002_auto_20160706_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='img', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=255, verbose_name='总结'),
        ),
    ]
