# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0003_auto_20160708_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='_userprofile_friends_+', to='BBS.UserProfile'),
        ),
    ]
